### ISSUE TITLE
Caused by: android.support.v8.renderscript.RSIllegalArgumentException: Unsuported element type.

### ISSUE THREAD

**Issue by Wbaokang** [jrvansuita/GaussianBlur#2]
Hello,when i use GaussianBlur to deal with a picture ,it throws this Exception,My picture is got from web  async through Glide,and below is my code:

```
public class MainActivity extends AppCompatActivity {
    ImageView ivStone;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        ivStone = (ImageView) findViewById(R.id.stone);

        Glide.with(this).load("http://pic6.huitu.com/res/20130116/84481_20130116142820494200_1.jpg").asBitmap().into(new SimpleTarget<Bitmap>() {
            @Override
            public void onResourceReady(Bitmap resource, GlideAnimation<? super Bitmap> glideAnimation) {
                Log.e("XXXX","onResourceReady"+resource.toString());
                setHeaderImage(resource);
            }

            @Override
            public void onLoadFailed(Exception e, Drawable errorDrawable) {
                Log.e("XXXX","onLoadFailed"+e.toString());
                setHeaderImage(BitmapFactory.decodeResource(getResources(), R.mipmap.dream_plan_detail_default_bg));
            }

            @Override
            public void onLoadStarted(Drawable placeholder) {
                Log.e("XXXX","onLoadStarted"+placeholder.toString());
                setHeaderImage(BitmapFactory.decodeResource(getResources(), R.mipmap.dream_plan_detail_default_bg));
            }
        });
    }
    private void setHeaderImage(Bitmap resource) {
        Log.e("XXXX","resource"+resource.toString());
        GaussianBlur.with(this).maxSixe(400).radius(5).put(resource, ivStone);
    }
}
```

**Comment by jrvansuita** [comment]
Can you paste here the entire stack trace?

**Comment by ashish0707** [comment]
stack=java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v8/renderscript/RenderScript;
             at com.vansuita.gaussianblur.GaussianBlur.render(GaussianBlur.java:42)
             at com.vansuita.gaussianblur.GaussianBlur.render(GaussianBlur.java:38)
             at madcourse.neu.edu.ashishbulchandani.MainActivity.onCreate(MainActivity.java:22)
             at android.app.Activity.performCreate(Activity.java:6876)
             at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
             at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
             at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
             at android.app.ActivityThread.access$1100(ActivityThread.java:222)
             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
             at android.os.Handler.dispatchMessage(Handler.java:102)
             at android.os.Looper.loop(Looper.java:158)
             at android.app.ActivityThread.main(ActivityThread.java:7229)
             at java.lang.reflect.Method.invoke(Native Method)
             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
          Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v8.renderscript.RenderScript" on path: DexPathList[[dex file "/data/data/madcourse.neu.edu.ashishbulchandani/files/instant-run/dex/slice-support-annotations-25.1.0_44e91aa230a718f2cef5a58783022166227d6fab-classes.dex", dex file "/data/data/madcourse.neu.edu.ashishbulchandani/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/madcourse.neu.edu.ashishbulchandani/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/madcourse.neu.edu.ashishbulchandani/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/madcourse.neu.edu.ashishbulchandani/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/madcourse.neu.edu.ashishbulchandani/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/madcourse.neu.edu.ashishbulchandani/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/madcourse.neu.edu.ashishbulchandani/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/madcourse.neu.edu.ashishbulchandani/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/madcourse.neu.edu.ashishbulchandani/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/madcourse.neu.edu.ashishbulchandani/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/madcourse.neu.edu.ashishbulchandani/files/instant-run/dex/slice-com.github.traex.rippleeffect-library-1.3_273370eb8f66dab29943178f88bbfdea28dfcc8d-classes.dex", dex file "/data/data/madcourse.neu.edu.ashishbulchandani/files/instant-run/dex/slice-com.github.jrvansuita-GaussianBlur-v1.0.2_efbc31079a1077b325424370efa8e4197e62a39c-classes.dex", dex file "/data/data/madcourse.neu.edu.ashishbulchandani/files/instant-run/dex/slice-com.android.support-support-vector-drawable-25.1.0_7b6b0acd541f46de5b769c411851f6a57eefa406-classes.dex", dex file "/data/data/madcourse.neu.edu.ashishbulchandani/files/instant-run/dex/slice-com.android.support-support-v4-25.1.0_cbb05c3f617a7011801db822c1c547f95a9a4062-classes.dex", dex file "/data/data/madcourse.neu.edu.ashishbulchandani/files/instant-run/dex/slice-com.android.support-support-media-compat-25.1.0_5f5ccb27ca25beca840b1c4701da865707959c5f-classes.dex", dex file "/data/data/madcourse.neu.edu.ashishbulchandani/files/instant-run/dex/slice-com.android.support-support-fragment-25.1.0_a10c7b1fdd2a8bb10fb90323dd5b212d0ce6db38-classes.dex", dex file "/data/data/madcourse.neu.edu.ashishbulchandani/files/instant-run/dex/slice-com.android.support-support-core-utils-25.1.0_159f8c3a2f5d7241ae4f655914977e9dafc6c466-classes.dex", dex file "/data/data/madcourse.neu.edu.ashishbulchandani/files/instant-run/dex/slice-com.android.support-support-core-ui-25.1.0_63f3ae6b20838459082b88cfdbe92e9f1bdce125-classes.dex", dex file "/data/data/madcourse.neu.edu.ashishbulchandani/files/instant-run/dex/slic

**Comment by jrvansuita** [comment]
Sorry for forget mention on readme file. You have to add this two lines on your build.gradle app module file.
```
 renderscriptTargetApi 19
 renderscriptSupportModeEnabled true
```

As is mentioned on the sample app build gradle file.

 ```
defaultConfig {
        applicationId "com.vansuita.gaussianblur.sample"
         minSdkVersion 9
         targetSdkVersion 25
         versionCode 1
         versionName "1.0"
 
         renderscriptTargetApi 19
         renderscriptSupportModeEnabled true
     }
```
